# docker-compose.yml
version: '3'
services:
  postgres:
    container_name: database
    image: postgres:11
    ports: ['5432:5432']
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - '9090:8080'

volumes:
  database-data: # named volumes can be managed easier using docker-compose